name: build-verify2

on:
  workflow_dispatch:

jobs:
  build-verify:
    runs-on: windows-2025
    timeout-minutes: 90
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-node@6